development:
  cloud_name: "dxmms7rbf"
  api_key: "669217294677112"
  api_secret: "EIMqlTL51wVjft4N2lWT0_B8WI0"
  secure: true
production:
  cloud_name: "dxmms7rbf"
  api_key: "669217294677112"
  api_secret: "EIMqlTL51wVjft4N2lWT0_B8WI0"
  secure: true
